language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  - cpanm --skip-satisfied -q -n Moo~2.002004 Gedcom Genealogy::Gedcom::Date Term::ANSIColor Lingua::EN::NameParse Lingua::EN::NameCase Tie::Static B::Lint warnings::unused IPC::System::Simple Term::ANSIColor DateTime::Format::Genealogy

script:
  - perl -c -MO=Lint ./gedcmp
  - perl -c -Mwarnings::unused ./gedcmp
